name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rust-ci:
    name: Build & Test Rust Backend
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.runCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s

    env:
      MONGO_URI: mongodb://localhost:27017
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-version: stable
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies (OpenSSL)
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Format check (cargo fmt)
        run: cargo fmt -- --check

      - name: Lint (cargo clippy)
        run: cargo clippy --all-targets --all-features -- -D warnings -A dead_code

      - name: Run tests
        run: cargo test
